### ISSUE TITLE
I am also trying to build astronomy software could you please let me know how to build this project?

### ISSUE THREAD

**Issue by sushiljic** [jeevika117/astrology#1]
Hi, i am from nepal and i am interested in astronomy project.
And i would like to build this project.
So could you please let me how to build this project.

**Comment by jeevika117** [comment]
Hey.. Its been long since i worked on this project.. i will take some time to check and tell you this.

**Comment by sushiljic** [comment]
@jeevika117 Thanks for the message and time.
I have started using Swiss Ephemeris file and Hope manual calculation will be now not necessary.
